version: "3"
services:
  # ===================================================================== s1 nginx
  s1:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    container_name: c1
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - "hunan:/changsha"
      - ${NGINX_CONF_DIR}:/etc/nginx/sites:ro
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${WWW_DIR}:/www:rw
      - ../0000_laravel:/0000
      - ../0001_vue:/0001:rw
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - youshengyouse
  # ===================================================================== s2 php
  s2:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: "$TZ"
    container_name: c2
    volumes:
      - ${WWW_DIR}:/www:rw
      - ${PHP_SOCKET_DIR}:/var/run:rw
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_ZZ_FILE}:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
      - ../0000_laravel:/0000
      - ${PWD}:/root
      - "hunan:/changsha"
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - youshengyouse
  # ===================================================================== s3 mysql
  s3:
    image: mysql:${MYSQL5_VERSION}
    container_name: c3
    ports:
      - "${MYSQL5_HOST_PORT}:3306"
    volumes:
      - ${MYSQL5_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql5:/var/lib/mysql/:rw
    restart: always
    networks:
      - youshengyouse
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL5_ROOT_PASSWORD}"
      TZ: "$TZ"
  # ===================================================================== s4 phpmyadmin
  s4:
    image: phpmyadmin/phpmyadmin:latest
    container_name: c4
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    volumes:
      - ${PHPMYADMIN_USER_CONF_FILE}:/etc/phpmyadmin/config.user.inc.php:ro
      - ${PHPMYADMIN_PHP_CONF_FILE}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini:ro
    networks:
      - youshengyouse
    environment:
      - PMA_HOST=s3
      - PMA_PORT=3306
      - TZ=$TZ
  # ===================================================================== s5 redis
  s5:
    image: redis:${REDIS_VERSION}
    container_name: c5
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      - youshengyouse
networks:
  youshengyouse:
volumes:
  hunan:
